# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviefun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalseasons', models.CharField(default='N/A', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tvplay',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='tvplay',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='tvplay',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tvplay',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbrating',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbvotes',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='tvplay',
            name='episode',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='tvplay',
            name='season',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='tvplay',
            name='seriesid',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='loc',
            name='city',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='loc',
            name='country',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='loc',
            name='latitude',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='loc',
            name='longitude',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviefun.Movie'),
        ),
    ]
