# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('imdbid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
