# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefun', '0002_auto_20161019_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='metascore',
        ),
    ]
